name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [release]

jobs:
  sign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Get artifact ID
        uses: actions/github-script@v7
        id: get-artifact-id
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: '${{ github.event.workflow_run.id }}',
            });
            return allArtifacts.data.artifacts[0].id;

      - name: Sign the build
        uses: signpath/github-action-submit-signing-request@v1
        with:
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          organization-id: ${{ secrets.SIGNPATH_ORG_ID }}
          project-slug: parsec-vdd
          signing-policy-slug: release-signing
          artifact-configuration-slug: portable-app
          github-artifact-id: "${{ steps.get-artifact-id.outputs.result }}"
          wait-for-completion: true
          output-artifact-directory: release
          parameters: |
            Version: "${{ github.ref_name }}"

      - name: Upload signed output
        uses: actions/upload-artifact@v4
        with:
          name: ParsecVDisplay-release
          path: |
            release/
